### ISSUE TITLE
How to link to a certain section on a page in navigation.yml

### ISSUE THREAD

**Issue by Jimbo994** [Phlow/feeling-responsive#226]
Hi,

So, I'd like to have a dropdown menu as shown below:

- title: "Lab"
  url: "/lab/"
  side: right
  dropdown:
  - title: "People"
    url: "/people/"
  - title: "Associate Members"
    url: "/people/"

However, I want the "Associate Members" menu option to link to the people section at a certain line instead of having it start at the beginning. How would I be able to do that? Do you have any ideas?

Thanks in advance,
Jim

**Comment by markcmiller86** [comment]
I just tested something like this and it worked...

```
- title: Home
  url: "/"
  side: left
  dropdown:
  - title: "About"
    url: "/about/"
  - title: "Getting help"
    url: "/support/#supported-platforms"
  - title: "Examples/Gallery"
    url: "/examples/"
.
.
.
```

Note the line with `#supported-platforms`.

Of course, the anchor you are sending to has to exist either because you have an explicit `<a name=anchor-name></a>` or you are using an implici built-in anchor defined by any of the underlying technologies (markdown, liquid, your layouts, etc).
