### ISSUE TITLE
Header Images not loading

### ISSUE THREAD

**Issue by RichNSD** [Phlow/feeling-responsive#252]
# Summary

The only full-width 'hero' image that loads correctly right now is on the Homepage, which is still the original file that came with the template:

```
~/pages/pages-root-folder/index.md
```

All other pages in the `~/pages` folder build, but the space where the header image goes is currently empty.

<br />

# Details

| Item  | URL  |
| :---: | :--- |
| GitHub Repository | https://github.com/NewSpectrum/Technovine-Site |
| GH-Pages Host | https://site.technovinesolutions.com/ |

The repository is public so if you need to see anything from the files you can check them out there.

### Config Summary

Filtered information from the [`_config.yml`](https://github.com/NewSpectrum/Technovine-Site/blob/gh-pages/_config.yml)

```yaml
# Site Settings
title: 'Technovine Solutions'
description: 'IT Solutions.'

author: RichNSD

url: 'https://site.technovinesolutions.com'
baseurl: '/'

improve_content: https://github.com/NewSpectrum/Technovine-Site/edit/gh-pages

urlimg: 'https://site.technovinesolutions.com/images/'

logo: "Fulll Logo (Site) [F].png"

plugins:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate


# Defaults
defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      show_meta: false
      sidebar: left
      comments: false
      author: RichNSD
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true
      sidebar: left
      comments: false
      author: PatriotsForLife
```

### Frontmatter

The YAML frontmatter from the [About](https://site.technovinesolutions.com/about) page

Source: [`about.md`](https://github.com/NewSpectrum/Technovine-Site/blob/gh-pages/pages/about.md)

```
layout: page
permalink: /about

title: "About"
subheadline: ""

header: yes
header:
    image_fullwidth: yes
    image: "about-002.jpeg"
    color: # "hsla(0, 0%, 10%, 1.0)" (text)
    background-color: "hsla(43, 100%, 100%, 1.0)"
    title: # "Title Text"

sidebar: left
meta_title: # Enter later
meta_description: # "Page Description"
tags:
  - 

homepage: false
```

Let me know if you need any other information.
