### ISSUE TITLE
Single line blockquotes look strange

### ISSUE THREAD

**Issue by TWiStErRob** [Phlow/feeling-responsive#26]
Take a glance at https://phlow.github.io/feeling-responsive/design/typography/#typographical-elements
The single-line quotation starts with a lower >> and ends with an upper <<.
The multi-line quotation starts with an upper >> and ends with a lower <<.
This feels inconsistent, is there a rule for such a thing?
If not, here's how I changed `_06_typography` it which looks good for both:

```scss
    &:before {
        //display: block; // blockquote is a block
        content: "\00BB";
        font-size: 80px;
        line-height: 0; // new
        position: absolute;
        left: -25px;
        top: auto; // was -40px
        color: $secondary-color;
    }
    &:after {
        //display: block; // blockquote is a block
        content: "\00AB";
        font-size: 80px;
        line-height: 0; // new
        position: absolute;
        right: -10px;
        bottom: 20px; // was -40px
        color: $secondary-color;
    }
```
