### ISSUE TITLE
layout: blog and permalink: index.html does not work?

### ISSUE THREAD

**Issue by n00btotal** [Phlow/feeling-responsive#84]
I'm trying to list blog entries as a "homepage", or rather, I', trying to get the blog-layout as a index.html page.

Like this

```

---
layout: blog
title: "Feeling responsive"
teaser: "Great them yo! Check out the blog entries!"
header:
    image_fullwidth: "header-bus.jpg"

permalink: /index.html

---
```

But I get no blog listing. Just a link to the archives (the archives work as expected!).

Any suggestions

**Comment by TWiStErRob** [comment]
I think you need to play with `paginate_path` in `_config.yml` because you're esentially relocating `/blog/` to `/`.

**Comment by n00btotal** [comment]
Great tip! Thanks!

After playing around with paginate_path in _config.yml for a while I ended upp with 

```
paginate_path: "page:num"
```

And placed index.html in the root directory

```
---
layout: blog
title: "Feeling responsive"
teaser: "Great them yo! Check out the blog entries!"
header:
    image_fullwidth: "header-bus.jpg"
    permalink: /
---
```

I also had to change _includes/_pagination.html , since the links in pagination has the "blog/ directory "hardcoded".

Please note that I'm kind of new to jekyll and jekyll-pagination..
