### ISSUE TITLE
Only posts starting with years <= 2015 are shown

### ISSUE THREAD

**Issue by wnuesser** [Phlow/feeling-responsive#92]
Hi,

a strange behaviour in my first "Feeling Responsive" web site:
only posts in _posts subdirectory with a year in the name <= 2015
are shown. 

Ex:
2016-04-28-test.md is not shown.
Simply renaming it to 2015-04-28-test.md .... and it shows up again.

Debugging jekyll I couldn't find the culprit: there seems to be no
hard coded upper limit.

Am I too stupid?

TIA
   Willi

**Comment by TWiStErRob** [comment]
Try renaming it to `2016-04-21` (=yesterday)... and/or change the settings in `_config.yml`:

``` yml
show_drafts: true|false
future:      true|false
unpublished: true|false
```

See https://jekyllrb.com/docs/configuration/ for description of these configs.
